//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstantRemote.Core.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageServices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageServices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegrationService.Core.Messages.MessageServices", typeof(MessageServices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad headers.
        /// </summary>
        public static string BadHeaders {
            get {
                return ResourceManager.GetString("BadHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelación por usuario.
        /// </summary>
        public static string CommentsCore {
            get {
                return ResourceManager.GetString("CommentsCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred: Balance not found.
        /// </summary>
        public static string CreateInvestmentAccountBalanceNotFound {
            get {
                return ResourceManager.GetString("CreateInvestmentAccountBalanceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred: Insufficient funds.
        /// </summary>
        public static string CreateInvestmentAccountInsufficientFunds {
            get {
                return ResourceManager.GetString("CreateInvestmentAccountInsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred: Savings account not found.
        /// </summary>
        public static string CreateInvestmentAccountSavingsAccountNotFound {
            get {
                return ResourceManager.GetString("CreateInvestmentAccountSavingsAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin Tarea cancelación autómatica solicitud de crédito, cancelados {0}.
        /// </summary>
        public static string EndTask {
            get {
                return ResourceManager.GetString("EndTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Process.
        /// </summary>
        public static string InvalidProcess {
            get {
                return ResourceManager.GetString("InvalidProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred: ServiceCore no content .
        /// </summary>
        public static string KOCoreBank {
            get {
                return ResourceManager.GetString("KOCoreBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocuured: ServiceDigiPro in confilct .
        /// </summary>
        public static string KODigipro {
            get {
                return ResourceManager.GetString("KODigipro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al hacer el depósito.
        /// </summary>
        public static string KOOnsigna {
            get {
                return ResourceManager.GetString("KOOnsigna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KO.
        /// </summary>
        public static string KOResponseGenerate {
            get {
                return ResourceManager.GetString("KOResponseGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred: no register one address for user given.
        /// </summary>
        public static string KOResponseGetAddress {
            get {
                return ResourceManager.GetString("KOResponseGetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred: EXPIRED_SEED.
        /// </summary>
        public static string KOResponseSignIn {
            get {
                return ResourceManager.GetString("KOResponseSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred: empty Seed by entered parameters.
        /// </summary>
        public static string KOResponseSignInNull {
            get {
                return ResourceManager.GetString("KOResponseSignInNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KO.
        /// </summary>
        public static string KOResponseTeChreo {
            get {
                return ResourceManager.GetString("KOResponseTeChreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred: Service Salesforce in conflict.
        /// </summary>
        public static string KOSalesForce {
            get {
                return ResourceManager.GetString("KOSalesForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la solicitud del seguro.
        /// </summary>
        public static string NotFoundInsuranceRequest {
            get {
                return ResourceManager.GetString("NotFoundInsuranceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el cliente.
        /// </summary>
        public static string NotFoundPerson {
            get {
                return ResourceManager.GetString("NotFoundPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro la cuenta.
        /// </summary>
        public static string NotFountLoan {
            get {
                return ResourceManager.GetString("NotFountLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SESSION_IN.
        /// </summary>
        public static string OkResponseGenerate {
            get {
                return ResourceManager.GetString("OkResponseGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred: process complete user not found.
        /// </summary>
        public static string OKResponseGenerate204 {
            get {
                return ResourceManager.GetString("OKResponseGenerate204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKResponseTeChreo {
            get {
                return ResourceManager.GetString("OKResponseTeChreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya tiene un crédito activo.
        /// </summary>
        public static string PendingRequest {
            get {
                return ResourceManager.GetString("PendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: search_request_scud.
        /// </summary>
        public static string ScudServiceErrorSearchRequest {
            get {
                return ResourceManager.GetString("ScudServiceErrorSearchRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: invalid_unique_customer_scud.
        /// </summary>
        public static string ScudServiceErrorUniqueCustomer {
            get {
                return ResourceManager.GetString("ScudServiceErrorUniqueCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio Tarea cancelación autómatica solicitud de crédito.
        /// </summary>
        public static string StartTask {
            get {
                return ResourceManager.GetString("StartTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without active loan.
        /// </summary>
        public static string WithoutActiveLoan {
            get {
                return ResourceManager.GetString("WithoutActiveLoan", resourceCulture);
            }
        }
    }
}
